# Generated by Django 4.2.1 on 2023-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('chatTime', models.DateTimeField()),
                ('reading', models.BooleanField()),
                ('chatType', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatRoomID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
