# Generated by Django 4.2.1 on 2023-05-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('chatTime', models.DateTimeField(auto_now_add=True)),
                ('reading', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatRoomID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('chatRoomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
        ),
    ]
