# Generated by Django 4.2.1 on 2023-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chatType',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chatTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
