# Generated by Django 4.2.1 on 2023-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('chatTime', models.DateTimeField()),
                ('reading', models.BooleanField()),
                ('chatType', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatRoomID', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPost',
            fields=[
                ('product_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('postTitle', models.CharField(default='', max_length=30)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('postContents', models.TextField()),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(default='', max_length=15)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
