# Generated by Django 4.2.1 on 2023-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('chatTime', models.DateTimeField()),
                ('reading', models.BooleanField()),
                ('chatType', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatRoomID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPost',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('postTitle', models.CharField(default='', max_length=30)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('postContents', models.TextField()),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
