# Generated by Django 4.2.1 on 2023-05-31 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upload',
            name='postID',
            field=models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.productpost'),
        ),
        migrations.AddField(
            model_name='upload',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradingreview',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productpost'),
        ),
        migrations.AddField(
            model_name='tradingreview',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productpost'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productpost'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
