# Generated by Django 4.2.1 on 2023-05-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpost',
            name='postTime',
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('postingID', models.AutoField(primary_key=True, serialize=False)),
                ('postingTime', models.DateTimeField(auto_now_add=True)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.productpost')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
