# Generated by Django 4.2.1 on 2023-05-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchasehistory_saleshistory_upload_wishlist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
