# Generated by Django 4.2.1 on 2023-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
